config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    	 to: 'static_pages#help'
  # get  '/about',     to: 'static_pages#about'
  # get  '/contact',   to: 'static_pages#contact'
  get  '/timeline',  to: 'posts#timeline'
  get  '/ranking', 	 to: 'posts#ranking'
  get  '/signup',  	 to: 'users#new'
  post '/signup',  	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resource :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attachment :user_image, content_type: ["image/jpeg", "image/png", "image/gif"]

	attr_accessor :remember_token
	before_save { email.downcase! }
  validates :user_name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  scope :search_by_keyword, -> (keyword) {
    where("users.user_name LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%") if keyword.present?
  }

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    if params[:q]
      @users = User.search_by_keyword(params[:q])
                        .paginate(page: params[:page])
    else
      @users = User.paginate(page: params[:page])
    end
  end

	def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
    	flash[:success] = "ユーザー登録が完了しました！"
    	redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報の更新に成功しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if User.find(params[:id]).destroy
      flash[:success] = "ユーザーの削除に成功しました"
      redirect_to users_url
    else
      redirect_to root_path
    end
  end

  def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    @headline = "フォローしているユーザー"
    @message = "フォローしているユーザーはありません"
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    @headline = "フォロワーとなっているユーザー"
    @message = "フォロワーとなっているユーザーはありません"
    render 'show_follow'
  end
  
  private

    def user_params
      params.require(:user).permit(:user_name, :email, :user_image,
                                   :password, :password_confirmation)
    end

    # beforeアクション

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user?(@user) %>
	<%= link_to "新しい解説を投稿する", new_post_path, class: "btn btn-primary btn_new_post" %>
<% else %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'users/unfollow' %>
  <% else %>
    <%= render 'users/follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :user_name, "ユーザー名" %>
  <%= f.text_field :user_name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :user_image, "プロフィール画像 (設定がない場合は初期画像になります)" %>
  <%= f.attachment_field :user_image %>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード確認" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<% if user.user_image_id.nil? %>
    <%= link_to gravatar_for(user, size: 50), user %>
  <% else %>
    <%= link_to user_path(user) do %>
      <%= attachment_image_tag user, :user_image, :fill, 50, 50, format: 'jpeg', alt: "ユーザー画像", class: "user_image_small" %>
    <% end %>
  <% end %>

  <%= link_to user.user_name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "このユーザーを削除する", user, method: :delete,
                                  data: { confirm: "ユーザー：#{user.user_name} の削除を実行しますか?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザー情報変更') %>
<% provide(:url, user_path) %>
<% provide(:button_text, 'この内容で更新する') %>
<h1>ユーザー情報変更</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <% if @user.user_image_id.nil? %>
	    <div class="gravatar_edit">
	      <%= gravatar_for @user %>
	      <a href="http://gravatar.com/emails" target="_blank">Gravatarでプロフィール画像を変更する</a>
	    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<li class="search-nav">
  <%= form_tag(users_path, method: :get) do %>
    <div class="input-group">
      <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "ユーザー名をキーワードで検索" %>
      <span class="input-group-btn">
        <%= button_tag(class: "btn btn-default") do %>
           <i class="fas fa-search"></i>
        <% end %>
      </span>
    </div>
  <% end %>
</li>
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー登録') %>
<% provide(:url, signup_path) %>
<% provide(:button_text, 'この内容で登録する') %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <h1>
        <% if @user.user_image_id.nil? %>
          <%= gravatar_for @user %>
        <% else %>
          <%= attachment_image_tag @user, :user_image, :fill, 80, 80, format: 'jpeg', alt: "ユーザー画像", class: "user_image" %>
        <% end %>
        <%= @user.user_name %>
      </h1>
      <span><%= @user.posts.count %>件の投稿</span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'follow_form' if logged_in? %>
  </aside>
  <div class="col-md-9">
    <% if @user.posts.any? %>
      <h3>解説投稿：<%= @user.posts.count %> 件</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% else %>
      <h3>投稿はまだありません</h3>
      <hr>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <% if @user.user_image_id.nil? %>
        <%= link_to gravatar_for(@user, size: 80), @user %>
      <% else %>
        <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :user_image, :fill, 80, 80, format: 'jpeg', alt: "ユーザー画像" %>
        <% end %>
      <% end %>
      <h1><%= @user.user_name %></h1>
      <span><%= link_to "ユーザーページへ移動", @user %></span>
      <span><%= @user.posts.count %>件の投稿</span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <% if user.user_image_id.nil? %>
              <%= link_to gravatar_for(user, size: 30), user %>
            <% else %>
              <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :user_image, :fill, 30, 30, format: 'jpeg', alt: "ユーザー画像" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @users.any? %>
      <h3><%= @headline %></h3>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% else %>
      <h3><%= @message %></h3>
      <hr>
    <% end %>
  </div>
</div>