config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    	 to: 'static_pages#help'
  # get  '/about',     to: 'static_pages#about'
  # get  '/contact',   to: 'static_pages#contact'
  get  '/timeline',  to: 'posts#timeline'
  get  '/ranking', 	 to: 'posts#ranking'
  get  '/signup',  	 to: 'users#new'
  post '/signup',  	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resource :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力内容に<%= object.errors.count %>か所の間違いがあります
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= link_to "もっと見る...", timeline_path %>
<% else %>
	<hr>
	<p>フォロー中の投稿がありません</p>
<% end %>

app/views/shared/_link_list.html.erb
<%= link_to "タイムライン", timeline_path, class: "btn btn-default btn_selector" %>
<%= link_to "全ての解説", posts_path, class: "btn btn-default btn_selector" %>
<%= link_to "評価の高い解説", ranking_path, class: "btn btn-default btn_selector" %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<% if current_user.user_image_id.nil? %>
  <%= link_to gravatar_for(current_user, size: 80), current_user %>
<% else %>
  <%= link_to user_path(current_user) do %>
    <%= attachment_image_tag current_user, :user_image, :fill, 80, 80, format: 'jpeg', alt: "ユーザー画像", class: "user_image_small" %>
  <% end %>
<% end %>
<h1><%= current_user.user_name %></h1>
<span><%= link_to "ユーザーページへ移動", current_user %></span>
<span><%= current_user.posts.count %>件の投稿</span>