config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    	 to: 'static_pages#help'
  # get  '/about',     to: 'static_pages#about'
  # get  '/contact',   to: 'static_pages#contact'
  get  '/timeline',  to: 'posts#timeline'
  get  '/ranking', 	 to: 'posts#ranking'
  get  '/signup',  	 to: 'users#new'
  post '/signup',  	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resource :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
	attachment :post_image, content_type: ["image/jpeg", "image/png", "image/gif"]

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  scope :search_by_keyword, -> (keyword) {
    where("posts.post_name LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%") if keyword.present?
  }
  validates :user_id, 	presence: true
  validates :post_name, presence: true, length: { maximum: 80 }
  validates :introduction, length: { maximum: 80 }
  validates :sub_title, presence: true, length: { maximum: 50 }
  validates :content, 	presence: true

	has_many :headlines, dependent: :destroy, inverse_of: :post
	accepts_nested_attributes_for :headlines, reject_if: :all_blank, allow_destroy: true

	has_many :likes, dependent: :destroy
	has_many :like_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

	# 投稿をいいねする
  def like(user)
    likes.create(user_id: user.id)
  end

  # 投稿のいいねを解除する
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  # 現在のユーザーがいいねしている場合にtrueを返す
  def like?(user)
    like_users.include?(user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user
	before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @title    = "解説一覧"
    @headline = "解説一覧"
    @message  = "解説がありません"
    if params[:q]
      relation = Post.joins(:user)
      @posts = relation.merge(User.search_by_keyword(params[:q]))
                      .or(relation.search_by_keyword(params[:q]))
                      .paginate(page: params[:page])
      @title    = "検索結果"
      @headline = "検索結果"
      @message  = "検索に該当する解説がありません"
    else
      @posts = Post.paginate(page: params[:page])
    end
  end

	def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build if logged_in?
    @comments = @post.comments.paginate(page: params[:page])
	end

	def new
		@post = current_user.posts.build if logged_in?
    @headline = @post.headlines.build
	end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "「#{@post.post_name}」の投稿に成功しました！"
      redirect_to root_url
    else
      render 'posts/new'
    end
  end

	def edit
    @post = Post.find(params[:id])
	end

	def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "投稿内容の編集に成功しました！"
      redirect_to @post
    else
      render 'edit'
    end
	end

	def destroy
    if Post.find(params[:id]).destroy
      flash[:success] = "「#{@post.post_name}」を削除しました！"
      redirect_to root_path
    else
      redirect_to root_path
    end
	end

  def timeline
    @posts = current_user.feed.paginate(page: params[:page])
  end

  def ranking
    # @posts = Post.find(Like.group(:post_id).order('count(post_id) desc').pluck(:post_id))

    # @posts = Post.select('posts.*', 'count(likes.id) AS likes').left_joins(:likes).group('posts.id').order('likes desc').paginate(page: params[:page])
  
    @posts = Post.all.sort_by{ |k, v| k.likes.count }.reverse.paginate(page: params[:page])
  end

  private

    def post_params
      params.require(:post).permit(:post_name, :introduction, :post_image, :sub_title, :content,
                                   headlines_attributes: [:id, :headline_name, :headline_content, :_destroy])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
			<div class="comment_img_box">
				<% if comment.user.user_image_id.nil? %>
          <%= gravatar_for comment.user %>
        <% else %>
          <%= attachment_image_tag comment.user, :user_image, :fill, 80, 80, format: 'jpeg', alt: "ユーザー画像", class: "user_image" %>
        <% end %>
        <%= link_to @post.user.user_name, user_path(@post.user) %>
	  	</div>
			<div class="comment_user_box">
  			<%= comment.user.user_name %>
			</div>
			<div class="comment_content_box">
  			<%= comment.comment_content %>
			</div>
			<div class="comment_options_box">
  			<% if logged_in? && current_user.id == comment.user_id %>
	  			<%= link_to 'コメントを消す', post_comments_path(@post.id, comment_id: comment.id), method: :delete, "data-confirm" => "本当にコメントを消しますか?" %>
	  		<% end %>
			</div>

app/views/posts/_form.html.erb
<%= form_for(@post, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :post_name, "タイトル（必要）" %>
  <%= f.text_field :post_name, placeholder: "タイトルを入力してください", class: 'form-control' %>

  <%= f.label :introduction, "概要" %>
  <%= f.text_field :introduction, placeholder: "概要を入力してください(空白可)", class: 'form-control' %>

  <%= f.label :post_image, "添付画像" %>
  <%= f.attachment_field :post_image %>

  <%= f.label :sub_title, "見出し (必要)" %>
  <%= f.text_field :sub_title, placeholder: "見出しを入力してください", class: 'form-control' %>

  <%= f.label :content, "本文（必要）" %>
  <%= f.text_area :content, placeholder: "本文を入力してください", rows: "10", cols: "50", class: 'form-control' %>

  <!-- 見出し・内容追加 -->
  <div class="field">
    <%= f.fields_for :headlines do |f| %>
      <%= render 'headline_fields', f: f %>
    <% end %>
  </div>

  <div class="field">
    <%= link_to_add_association '見出しを追加する', f, :headlines,
      data: { association_insertion_method: 'before' },
      class: "btn btn-info" %>
  </div>
  <!-- 見出し・内容追加終わり -->

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/posts/_headline_fields.html.erb
<div class="nested-fields">
	<div class=form-group>
		<%= f.label :headline_name, "見出し" %>
  	<%= f.text_field :headline_name, placeholder: "見出しを入力してください", class: 'form-control'%>

  	<%= f.label :headline_content, "本文" %>
  	<%= f.text_area :headline_content, placeholder: "本文を入力してください", rows: "10", cols: "50", class: 'form-control' %>
	</div>
  <%= link_to_remove_association "この見出しを消す", f, class: "btn btn-danger" %>
</div>

app/views/posts/_index.html.erb
<% if @posts_index.any? %>
  <ol class="posts">
    <%= render @posts_index %>
  </ol>
  <%= link_to "もっと見る...", posts_path %>
<% else %>
	<hr>
	<p>解説の投稿がありません</p>
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">

  <% if post.user.user_image_id.nil? %>
    <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <% else %>
    <%= link_to user_path(post.user) do %>
      <%= attachment_image_tag post.user, :user_image, :fill, 50, 50, format: 'jpeg', alt: "ユーザー画像", class: "user_image_small" %>
    <% end %>
  <% end %>

  <span class="user"><%= link_to post.user.user_name, post.user %></span>
  <span class="post_name"><%= link_to post.post_name, post %></span>
  <span class="introduction"><%= post.introduction %></span>
  <span class="timestamp">
    <%= post.created_at.strftime('%Y年%m月%d日 %H:%M') %>に投稿
    <% if current_user?(post.user) %>
      <%= content_tag :span, "いいね！#{post.likes_count}", class: "fas fa-thumbs-up post_user_like" %>
      <%= link_to "投稿を削除", post, method: :delete,
                                       data: { confirm: "「#{post.post_name}」を本当に削除しますか？" } %>
    <% end %>
    <%= render "likes/like", post: post %>
  </span>
</li>

app/views/posts/_ranking.html.erb
<% if @ranking.any? %>
  <ol class="posts">
    <%= render @ranking %>
  </ol>
  <%= link_to "もっと見る...", ranking_path %>
<% else %>
	<hr>
	<p>解説の投稿がありません</p>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "投稿編集") %>
<% provide(:url, post_path) %>
<% provide(:button_text, '編集を完了する') %>
<h1>投稿編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'shared/link_list' %>
    <%= link_to "新しい解説を投稿する", new_post_path, class: "btn btn-primary btn_new_post" %>
  </aside>

  <div class="col-md-9">
  	<div class="wrapper">
			<h3><%= @headline %></h3>
			<% if @posts.any? %>
			  <ol class="posts">
			    <%= render @posts %>
			  </ol>
			  <%= will_paginate %>
			<% else %>
				<hr>
				<h4><%= @message %></h4>
			<% end %>
  	</div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>
<% provide(:url, posts_path) %>
<% provide(:button_text, 'この内容で投稿する') %>
<h1>新規投稿</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/ranking.html.erb
<% provide(:title, "人気順解説") %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'shared/link_list' %>
    <%= link_to "新しい解説を投稿する", new_post_path, class: "btn btn-primary btn_new_post" %>
  </aside>

  <div class="col-md-9">
    <div class="wrapper">
      <h3>人気順解説</h3>
      <% if @posts.any? %>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% else %>
        <hr>
        <h4>解説がありません</h4>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.post_name ) %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info" id="post_show_user_info">
      <h1 class="poster">投稿者</h1>
      <h1>
        <% if @post.user.user_image_id.nil? %>
          <%= gravatar_for @post.user %>
        <% else %>
          <%= attachment_image_tag @post.user, :user_image, :fill, 80, 80, format: 'jpeg', alt: "ユーザー画像", class: "user_image" %>
        <% end %>
        <%= @post.user.user_name %>
      </h1>
      <span><%= link_to "ユーザーページへ移動", user_path(@post.user) %></span>
      <span><%= @post.user.posts.count %>件の投稿</span>
    </section>
  </aside>
  <article class="col-md-9" id="post-<%= @post.id %>"> <!-- idはいいね機能の実装に必要 -->
    <section class="post_info_section">
      <span class=""><%= @post.created_at.strftime('%Y年%m月%d日 %H:%M') %>に投稿</span>
      <% if @post.user == current_user %>
        <%= link_to '解説を削除する', post_path(@post.id), method: :delete,
                                       data: { confirm: "「#{@post.post_name}」を本当に削除しますか？" },
                                      class: "btn btn-danger" %>
        <%= link_to '内容を編集する', edit_post_path(@post), class: "btn btn-success" %>
      <% else %>
        <%= render "likes/like", post: @post %>
      <% end %>
    </section>
    <section class="post_section">
      <h1><%= @post.post_name %></h1>
      <span><%= @post.introduction %></span>

      <div class="post_image_wrapper">
        <%= attachment_image_tag @post, :post_image, alt: "解説用画像", class: "post_image" %>
      </div>
      <h2><%= @post.sub_title %></h2>
      <p><%= simple_format(@post.content) %></p>
    </section>
    <!-- cocoonを用いての解説追加部分 -->
    <section class="headline_section">
      <% @post.headlines.each do |headline| %>
        <h2><%= headline.headline_name %></h2>
        <p><%= simple_format(headline.headline_content) %></p>
      <% end %>
    </section>
    <!-- cocoonを用いての解説追加部分終わり -->
    <section class="comment_section">
      <h2>コメント（<%= @post.comments.count %>件）</h2>
      <ol class="posts">
        <%= render @comments %>
      </ol>
      <%= render 'comments/comment_form' %>
    </section>
  </article>
</div>

app/views/posts/timeline.html.erb
<% provide(:title, "タイムライン") %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'shared/link_list' %>
    <%= link_to "新しい解説を投稿する", new_post_path, class: "btn btn-primary btn_new_post" %>
  </aside>

  <div class="col-md-9">
    <div class="wrapper">
      <h3>タイムライン</h3>
      <% if @posts.any? %>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= will_paginate %>
      <% else %>
        <hr>
        <h4>フォロー中の投稿がありません</h4>
      <% end %>
    </div>
  </div>
</div>