config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    	 to: 'static_pages#help'
  # get  '/about',     to: 'static_pages#about'
  # get  '/contact',   to: 'static_pages#contact'
  get  '/timeline',  to: 'posts#timeline'
  get  '/ranking', 	 to: 'posts#ranking'
  get  '/signup',  	 to: 'users#new'
  post '/signup',  	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resource :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    HistoryPost is created by Nobuya Yanagisawa.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container header_container">
    <%= link_to "HistoryPost", root_path, data: {"turbolinks" => false}, id: "logo", class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation' %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarMain">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>

<div class="collapse navbar-collapse" id="navbarMain">
  <ul class="nav navbar-nav">
    <%= render 'layouts/search' %>
    <li><%= link_to "ホーム", root_path, data: {"turbolinks" => false}, class: "fas fa-home" %></li>
    <li><%= link_to "ヘルプ", help_path, class: "fas fa-question-circle" %></li>
    <% if logged_in? %>
      <li><%= link_to "ユーザー", users_path, class: "fas fa-users" %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle fas fa-user" data-toggle="dropdown">
          アカウント <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "マイページ", current_user %></li>
          <li><%= link_to "ユーザー情報変更", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "ログアウト", logout_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "ログイン", login_path, class: "fas fa-sign-in-alt" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_search.html.erb
<% if logged_in? %>
  <li class="search-nav">
    <%= form_tag(posts_path, method: :get) do %>
      <div class="input-group">
        <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "解説をキーワードで検索" %>
        <span class="input-group-btn">
          <%= button_tag(class: "btn btn-default") do %>
            <i class="fas fa-search"></i>
          <% end %>
        </span>
      </div>
    <% end %>
  </li>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <link href="https://fonts.googleapis.com/css?family=Germania+One|Lobster" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css" integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y" crossorigin="anonymous">
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>